package proyectocalculadora;

import proyectocalculadora.Calculadora;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author elenalunapalacio
 */
public class CalculadoraGUI extends javax.swing.JFrame {

    /**
     * Creates new form CalculadoraGUI
     */
    public CalculadoraGUI() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtPantalla = new javax.swing.JTextField();
        sieteB = new javax.swing.JButton();
        ochoB = new javax.swing.JButton();
        nueveB = new javax.swing.JButton();
        cuatroB = new javax.swing.JButton();
        cincoB = new javax.swing.JButton();
        seisB = new javax.swing.JButton();
        unoB = new javax.swing.JButton();
        dosB = new javax.swing.JButton();
        tresB = new javax.swing.JButton();
        ceroB = new javax.swing.JButton();
        puntoB = new javax.swing.JButton();
        igualB = new javax.swing.JButton();
        divB = new javax.swing.JButton();
        porB = new javax.swing.JButton();
        restaB = new javax.swing.JButton();
        sumaB = new javax.swing.JButton();
        clearB = new javax.swing.JButton();
        parIzqB = new javax.swing.JButton();
        parDerB = new javax.swing.JButton();
        deleteB = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(153, 204, 255));
        setForeground(java.awt.Color.white);

        txtPantalla.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtPantallaActionPerformed(evt);
            }
        });

        sieteB.setBackground(new java.awt.Color(102, 153, 255));
        sieteB.setForeground(new java.awt.Color(255, 255, 255));
        sieteB.setText("7");
        sieteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sieteBActionPerformed(evt);
            }
        });

        ochoB.setBackground(new java.awt.Color(102, 153, 255));
        ochoB.setForeground(new java.awt.Color(255, 255, 255));
        ochoB.setText("8");
        ochoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ochoBActionPerformed(evt);
            }
        });

        nueveB.setBackground(new java.awt.Color(102, 153, 255));
        nueveB.setForeground(new java.awt.Color(255, 255, 255));
        nueveB.setText("9");
        nueveB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nueveBActionPerformed(evt);
            }
        });

        cuatroB.setBackground(new java.awt.Color(102, 153, 255));
        cuatroB.setForeground(new java.awt.Color(255, 255, 255));
        cuatroB.setText("4");
        cuatroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cuatroBActionPerformed(evt);
            }
        });

        cincoB.setBackground(new java.awt.Color(102, 153, 255));
        cincoB.setForeground(new java.awt.Color(255, 255, 255));
        cincoB.setText("5");
        cincoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cincoBActionPerformed(evt);
            }
        });

        seisB.setBackground(new java.awt.Color(102, 153, 255));
        seisB.setForeground(new java.awt.Color(255, 255, 255));
        seisB.setText("6");
        seisB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                seisBActionPerformed(evt);
            }
        });

        unoB.setBackground(new java.awt.Color(102, 153, 255));
        unoB.setForeground(new java.awt.Color(255, 255, 255));
        unoB.setText("1");
        unoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                unoBActionPerformed(evt);
            }
        });

        dosB.setBackground(new java.awt.Color(102, 153, 255));
        dosB.setForeground(new java.awt.Color(255, 255, 255));
        dosB.setText("2");
        dosB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosBActionPerformed(evt);
            }
        });

        tresB.setBackground(new java.awt.Color(102, 153, 255));
        tresB.setForeground(new java.awt.Color(255, 255, 255));
        tresB.setText("3");
        tresB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tresBActionPerformed(evt);
            }
        });

        ceroB.setBackground(new java.awt.Color(102, 153, 255));
        ceroB.setForeground(new java.awt.Color(255, 255, 255));
        ceroB.setText("0");
        ceroB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ceroBActionPerformed(evt);
            }
        });

        puntoB.setBackground(new java.awt.Color(204, 204, 255));
        puntoB.setText(".");
        puntoB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                puntoBActionPerformed(evt);
            }
        });

        igualB.setBackground(new java.awt.Color(255, 204, 204));
        igualB.setText("=");
        igualB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                igualBActionPerformed(evt);
            }
        });

        divB.setBackground(new java.awt.Color(204, 204, 255));
        divB.setText("/");
        divB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                divBActionPerformed(evt);
            }
        });

        porB.setBackground(new java.awt.Color(204, 204, 255));
        porB.setText("x");
        porB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                porBActionPerformed(evt);
            }
        });

        restaB.setBackground(new java.awt.Color(204, 204, 255));
        restaB.setText("-");
        restaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                restaBActionPerformed(evt);
            }
        });

        sumaB.setBackground(new java.awt.Color(204, 204, 255));
        sumaB.setText("+");
        sumaB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sumaBActionPerformed(evt);
            }
        });

        clearB.setBackground(new java.awt.Color(255, 204, 204));
        clearB.setText("C");
        clearB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearBActionPerformed(evt);
            }
        });

        parIzqB.setBackground(new java.awt.Color(204, 204, 255));
        parIzqB.setText("(");
        parIzqB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parIzqBActionPerformed(evt);
            }
        });

        parDerB.setBackground(new java.awt.Color(204, 204, 255));
        parDerB.setText(")");
        parDerB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parDerBActionPerformed(evt);
            }
        });

        deleteB.setBackground(new java.awt.Color(255, 204, 204));
        deleteB.setText("DEL");
        deleteB.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                deleteBActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(39, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(txtPantalla)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ceroB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cuatroB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sieteB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(unoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(ochoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(cincoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(dosB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(puntoB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(nueveB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(seisB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(tresB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(igualB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(divB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(porB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(restaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(sumaB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(parDerB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(clearB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(parIzqB, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(deleteB, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                .addGap(45, 45, 45))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(txtPantalla, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(sieteB)
                    .addComponent(ochoB)
                    .addComponent(nueveB)
                    .addComponent(divB)
                    .addComponent(deleteB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cuatroB)
                    .addComponent(cincoB)
                    .addComponent(seisB)
                    .addComponent(porB)
                    .addComponent(clearB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(unoB)
                    .addComponent(dosB)
                    .addComponent(tresB)
                    .addComponent(restaB)
                    .addComponent(parIzqB))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(ceroB)
                    .addComponent(puntoB)
                    .addComponent(igualB)
                    .addComponent(sumaB)
                    .addComponent(parDerB))
                .addContainerGap(30, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tresBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tresBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"3");
    }//GEN-LAST:event_tresBActionPerformed

    private void ceroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ceroBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"0");
    }//GEN-LAST:event_ceroBActionPerformed

    private void unoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_unoBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"1");
    }//GEN-LAST:event_unoBActionPerformed

    private void sieteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sieteBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"7");
    }//GEN-LAST:event_sieteBActionPerformed

    private void ochoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ochoBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"8");
    }//GEN-LAST:event_ochoBActionPerformed

    private void nueveBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nueveBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"9");
    }//GEN-LAST:event_nueveBActionPerformed

    private void divBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_divBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"/");
    }//GEN-LAST:event_divBActionPerformed

    private void deleteBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_deleteBActionPerformed
        // TODO add your handling code here:
       
        String txt = txtPantalla.getText();
        StringBuffer sb = new StringBuffer(txt);
        int pos = txt.length() - 1;
        sb.deleteCharAt(pos);
        txtPantalla.setText(sb.toString());
        
        
    }//GEN-LAST:event_deleteBActionPerformed

    private void cuatroBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cuatroBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"4");
    }//GEN-LAST:event_cuatroBActionPerformed

    private void cincoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cincoBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"5");

    }//GEN-LAST:event_cincoBActionPerformed

    private void seisBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_seisBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"6");

    }//GEN-LAST:event_seisBActionPerformed

    private void porBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_porBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"*");
        
    }//GEN-LAST:event_porBActionPerformed

    private void clearBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText("");
        
    }//GEN-LAST:event_clearBActionPerformed

    private void dosBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"2");
    }//GEN-LAST:event_dosBActionPerformed

    private void restaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_restaBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"-");
        
    }//GEN-LAST:event_restaBActionPerformed

    private void parIzqBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parIzqBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"(");
    }//GEN-LAST:event_parIzqBActionPerformed

    private void puntoBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_puntoBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+".");
    }//GEN-LAST:event_puntoBActionPerformed

    private void igualBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_igualBActionPerformed
        // TODO add your handling code here:
        String entrada = txtPantalla.getText();
        try{
            String resultado = Calculadora.calcula(entrada);
            txtPantalla.setText(resultado);
        } catch(Exception e){
            txtPantalla.setText(e.getMessage());
        }
    


        
        
    }//GEN-LAST:event_igualBActionPerformed

    private void sumaBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sumaBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+"+");
    }//GEN-LAST:event_sumaBActionPerformed

    private void parDerBActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_parDerBActionPerformed
        // TODO add your handling code here:
        txtPantalla.setText(txtPantalla.getText()+")");
    }//GEN-LAST:event_parDerBActionPerformed

    private void txtPantallaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtPantallaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPantallaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(CalculadoraGUI.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new CalculadoraGUI().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ceroB;
    private javax.swing.JButton cincoB;
    private javax.swing.JButton clearB;
    private javax.swing.JButton cuatroB;
    private javax.swing.JButton deleteB;
    private javax.swing.JButton divB;
    private javax.swing.JButton dosB;
    private javax.swing.JButton igualB;
    private javax.swing.JButton nueveB;
    private javax.swing.JButton ochoB;
    private javax.swing.JButton parDerB;
    private javax.swing.JButton parIzqB;
    private javax.swing.JButton porB;
    private javax.swing.JButton puntoB;
    private javax.swing.JButton restaB;
    private javax.swing.JButton seisB;
    private javax.swing.JButton sieteB;
    private javax.swing.JButton sumaB;
    private javax.swing.JButton tresB;
    private javax.swing.JTextField txtPantalla;
    private javax.swing.JButton unoB;
    // End of variables declaration//GEN-END:variables
}

